// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6XKHPzBrtiNEcs0TChqKYOHLlvkm7sko',
    appId: '1:190573022680:web:62b5f6d2db18a509cd36ad',
    messagingSenderId: '190573022680',
    projectId: 'einsatzkleidung',
    authDomain: 'einsatzkleidung.firebaseapp.com',
    storageBucket: 'einsatzkleidung.firebasestorage.app',
    measurementId: 'G-YTMWDE6C25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyV3NJ80mmNsmDUSH2_ST1KEV5Hesl8Zg',
    appId: '1:190573022680:android:485c4fcdf4693e03cd36ad',
    messagingSenderId: '190573022680',
    projectId: 'einsatzkleidung',
    storageBucket: 'einsatzkleidung.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNKL7tqlie-SwZICcUVlU1RD6T7zDG1qg',
    appId: '1:190573022680:ios:4bc3b9108ce6d815cd36ad',
    messagingSenderId: '190573022680',
    projectId: 'einsatzkleidung',
    storageBucket: 'einsatzkleidung.firebasestorage.app',
    iosBundleId: 'com.example.kleidungsverwaltung2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6XKHPzBrtiNEcs0TChqKYOHLlvkm7sko',
    appId: '1:190573022680:web:0ee206faa92df277cd36ad',
    messagingSenderId: '190573022680',
    projectId: 'einsatzkleidung',
    authDomain: 'einsatzkleidung.firebaseapp.com',
    storageBucket: 'einsatzkleidung.firebasestorage.app',
    measurementId: 'G-VTLMGPF25M',
  );
}
